# Generated by Django 5.1.7 on 2025-03-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=50)),
                ('place_location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
    ]
