# Generated by Django 5.1.7 on 2025-03-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_service', models.CharField(max_length=50)),
                ('description_service', models.TextField()),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
    ]
