# Generated by Django 5.1.2 on 2025-04-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=50)),
                ('service_description', models.TextField()),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
    ]
